name: run-e2e-tests

on:
  push:
    branches: [ master ]

jobs:
    cypress-e2e:
      name: Cypress E2E with Allure
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: sudo apt-get update && sudo apt-get install -y allure

      - name: Run Cypress with Allure
        uses: cypress-io/github-actions@v6
        with:
          command: npx cypress run -s "cypress/e2e/cucumber/**/*.{feature,cy.js}" --env allure=true,allureResultsPath=allure-results
      
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          results-directory: allure-results
          report-directory: allure-report

      - name: Upload Allure Report (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*.mp4

      - name: Upload Failed Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-screenshots
          path: cypress/screenshots/
  
